name: check action
on: [push]
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hello world
          ls ${{ github.workspace }} -al
          ls -al
          pwd
          sh ./scripts/testing.sh