name: check action
on: [push]
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo hello world
          ls ${{ github.workspace }} -al
          ls -al
          pwd
          sh ./.github/scripts/testing.sh